---
title: Fordel
timezone: UTC
url: "http://fordel.agency"
baseurl: "" # the subpath of your site, e.g. /blog
email: hello@fordel.agency
description: Discerned. Delivered. Marketing that drives change.
permalink: pretty
twitter: https://twitter.com/dansallai
linkedin: https://www.linkedin.com/company/fordel
blog: https://blog.fordel.agency
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
gems:
  - jekyll-redirect-from
