---
title: Fordel
timezone: UTC
url: "http://fordel.agency"
baseurl: "" # the subpath of your site, e.g. /blog
email: hello@fordel.agency
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Discerned. Delivered. Marketing that drives change.
permalink: pretty
twitter: https://twitter.com/dansallai
github: https://github.com/<username>
linkedin-square: https://linkedin.com/in/<username>
facebook-official: https://facebook.com/<username>
google-plus-square: https://plus.google.com/u/0/+<username>
markdown: kramdown
